### PR TITLE
DMENU & TERMINAL SUPPORT (BOTH)

### PR DESCRIPTION
**Pull request by hackerW1**
Hi, I read issues and there were a guy like me who has a problem 'cause he don't use dmenu so I added terminal support in notflix (dmenu has not removed) and it is working fine so merge it but please check it once before merging. Thanks.

### CODE REVIEW

**Review by Noah-It-All — APPROVED** [review]

**Review by walkxcode — COMMENTED** [review]
Not working.

**Comment by hackerW1** [comment]
It's working with mine

**Comment by hackerW1** [comment]
> Not working.

what os are you using

**Review by Noah-It-All — COMMENTED** [review]
Now it isn't working for some reason, also only the list is moved to terminal, search stays the same

**Comment by walkxcode** [comment]
> > Not working.
> 
> what os are you using

Tried on different OS's. Doesn't work on any of them. Just install dmenu.

**Pull request closed without merging**
