### PR TITLE
Added webtorrent-cli installation through yay.

### PR DESCRIPTION
**Pull request by looph0le**

### CODE REVIEW

**Comment by adezxc** [comment]
I don't know why you would ever want to add yay, pacman or any other distro-specific tool to a readme when there's an widely used alternative.

**Comment by walkxcode** [comment]
This.

**Comment by walkxcode** [comment]
> I don't know why you would ever want to add yay, pacman or any other distro-specific tool to a readme when there's an widely used alternative.

This.

**Comment by looph0le** [comment]
> I don't know why you would ever want to add yay, pacman or any other distro-specific tool to a readme when there's an widely used alternative.

I understand, i tried installing it from npm itself but was unable to unfortunately.
yay worked for me, so might work for someone facing the same issue.

**Comment by walkxcode** [comment]
Seems like an issue on your end. npm is the official way to install webtorrent-cli, so there's no need to add `yay` to the notflix docs.

**Pull request closed without merging**
