### PR TITLE
Fix 1337x.to impostor

### PR DESCRIPTION
**Pull request by Willy-JL**
1337x.**wtf** is NOT an official domain for 1337x. The official website is 1337x.**to** and you can check the official domains [here](https://1337x.to/about)

### CODE REVIEW

**Comment by Bugswriter** [comment]
but 1337x.to is ban most of the places 1337x.wtf is working for me. 
:(
 should we still change?

**Comment by LamprosPitsillos** [comment]
Just add a comment in the script, and those who have problems just uncomment it.And maybe ad some FAQ later on explain it.

**Comment by Willy-JL** [comment]
Perhaps keep an array of the official domains and loop through them to see the first that works (?)

**Comment by Willy-JL** [comment]
I made a little test script, but I don't know if a ping will be sufficient...
```bash
#!/bin/bash

declare -a domains
domains+=("1337x.to")
domains+=("1337x.st")
domains+=("1337x.ws")
domains+=("1337x.eu")
domains+=("1337x.se")
domains+=("1337x.is")
domains+=("1337x.gd")
domains+=("1337x.wtf")  # This is not an official 1337x domain, be careful when using it!

i=0
while true ; do
  domain="${domains[$i]}"
  ((i+=1))
  ping -i 0.002 -c 1 "$domain" > /dev/null 2>&1 || continue
  break
done
echo "Found domain '$domain'"
```
Please @Bugswriter or someone else with 1337x.to blocked can confirm if this works?

**Comment by vveig4** [comment]
Your script does work in bash for selecting an unblocked domain. However all the official 1337x domains have Cloudflare ddos protection, which messes up the curl request for some systems.

**Comment by Willy-JL** [comment]
> Your script does work in bash for selecting an unblocked domain. However all the official 1337x domains have Cloudflare ddos protection, which messes up the curl request for some systems.

ah, you mean that pinging and sending a request right after messes up the request? then instead of ping + curl it could just run the actual curl request in the loop...?

**Comment by Willy-JL** [comment]
@vveig4 can you try the latest push i made?

**Comment by Zekiah-A** [comment]
When the imposter is sus

**Pull request closed without merging**
