### PR TITLE
Choice to Download or Stream

### PR DESCRIPTION
**Pull request by Si-Ki**
Added choice to download or stream while keeping the originality of the script.

### CODE REVIEW

**Comment by misobarisic** [comment]
I'm definitely adding this to my fork of the script! Nice job

**Comment by Si-Ki** [comment]
Glad I could make it better 😄

**Comment by stl3** [comment]
Nice job - for those not wanting to use transmission-remote you can just change it to 
`[ $choice = Download ] && webtorrent download "$magnet" & notify-send "Starting Download..."`

**Comment by Si-Ki** [comment]
> 

Yeah I was going to mention it as well but then I figured that people can figure out this on their own... also, this pull request just got featured on BugsWriter's channel in his latest video 😀 I'm famous now lol 😂.

**Comment by Si-Ki** [comment]
> Nice job - for those not wanting to use transmission-remote you can just change it to `[ $choice = Download ] && webtorrent download "$magnet" & notify-send "Starting Download..."`

or anything else like aria2c or you choice of magnet link handler...

**Comment by Si-Ki** [comment]
since the script has been replaced with a much shorter and faster version, I'm closing this pull request and creating a new one on the new script, go check that one out.

**Pull request closed without merging**
